[project]
name = "m2probafi-apprentissage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
    "torchvision>=0.24.0",
    "bitsandbytes>=0.48.2",
    "datasets>=4.4.1",
    "evaluate>=0.4.6",
    "gensim>=4.4.0",
    "jupyter>=1.1.1",
    "mlflow>=3.6.0",
    "nltk>=3.9.2",
    "openai>=1.100.0",
    "peft>=0.18.0",
    "polars>=1.35.1",
    "pyyaml>=6.0.2",
    "rank-bm25>=0.2.2",
    "requests>=2.32.4",
    "rouge-score>=0.1.2",
    "sacrebleu>=2.5.1",
    "tqdm>=4.67.1",
    "transformers>=4.57.3",
    "trl>=0.25.1",
    "pytorch-lightning>=2.6.0",
    "open-clip-torch>=3.2.0",
    "matplotlib>=3.10.5",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

